package com.dannydobbi.realmsofcaltrice.structure;

import java.util.Random;

import net.minecraft.init.Blocks;
import net.minecraft.world.World;
import net.minecraft.world.gen.feature.WorldGenerator;
 
public class ArcLightStructure extends WorldGenerator {
 
        public boolean generate(World world, Random rand, int i, int j, int k) {
                world.setBlock(i + 0, j + 0, k + 0, Blocks.planks);
                world.setBlock(i + 0, j + 0, k + 1, Blocks.planks);
                world.setBlock(i + 0, j + 0, k + 2, Blocks.planks);
                world.setBlock(i + 0, j + 0, k + 3, Blocks.planks);
                world.setBlock(i + 0, j + 0, k + 4, Blocks.planks);
                world.setBlock(i + 0, j + 0, k + 5, Blocks.planks);
                world.setBlock(i + 0, j + 0, k + 6, Blocks.planks);
                world.setBlock(i + 0, j + 0, k + 7, Blocks.planks);
                world.setBlock(i + 0, j + 0, k + 8, Blocks.planks);
                world.setBlock(i + 0, j + 0, k + 9, Blocks.planks);
                world.setBlock(i + 0, j + 0, k + 10, Blocks.planks);
                world.setBlock(i + 0, j + 0, k + 11, Blocks.planks);
                world.setBlock(i + 0, j + 0, k + 12, Blocks.planks);
                world.setBlock(i + 0, j + 0, k + 13, Blocks.planks);
                world.setBlock(i + 0, j + 0, k + 14, Blocks.planks);
                world.setBlock(i + 0, j + 0, k + 15, Blocks.planks);
                world.setBlock(i + 0, j + 0, k + 16, Blocks.planks);
                world.setBlock(i + 0, j + 0, k + 17, Blocks.planks);
                world.setBlock(i + 0, j + 1, k + 0, Blocks.stonebrick);
                world.setBlock(i + 0, j + 1, k + 1, Blocks.stonebrick);
                world.setBlock(i + 0, j + 1, k + 2, Blocks.stonebrick);
                world.setBlock(i + 0, j + 1, k + 3, Blocks.stonebrick);
                world.setBlock(i + 0, j + 1, k + 4, Blocks.stonebrick);
                world.setBlock(i + 0, j + 1, k + 5, Blocks.stonebrick);
                world.setBlock(i + 0, j + 1, k + 6, Blocks.stone_brick_stairs, 7, 2);
                world.setBlock(i + 0, j + 1, k + 11, Blocks.stone_brick_stairs, 6, 2);
                world.setBlock(i + 0, j + 1, k + 12, Blocks.stonebrick);
                world.setBlock(i + 0, j + 1, k + 13, Blocks.stonebrick);
                world.setBlock(i + 0, j + 1, k + 14, Blocks.stonebrick);
                world.setBlock(i + 0, j + 1, k + 15, Blocks.stonebrick);
                world.setBlock(i + 0, j + 1, k + 16, Blocks.stonebrick);
                world.setBlock(i + 0, j + 1, k + 17, Blocks.stonebrick);
                world.setBlock(i + 0, j + 2, k + 0, Blocks.stonebrick);
                world.setBlock(i + 0, j + 2, k + 1, Blocks.stonebrick);
                world.setBlock(i + 0, j + 2, k + 2, Blocks.stonebrick);
                world.setBlock(i + 0, j + 2, k + 3, Blocks.stonebrick);
                world.setBlock(i + 0, j + 2, k + 4, Blocks.stone_brick_stairs, 3, 2);
                world.setBlock(i + 0, j + 2, k + 5, Blocks.stone_brick_stairs, 2, 2);
                world.setBlock(i + 0, j + 2, k + 6, Blocks.stonebrick);
                world.setBlock(i + 0, j + 2, k + 7, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 0, j + 2, k + 10, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 0, j + 2, k + 11, Blocks.stonebrick);
                world.setBlock(i + 0, j + 2, k + 12, Blocks.stone_brick_stairs, 3, 2);
                world.setBlock(i + 0, j + 2, k + 13, Blocks.stone_brick_stairs, 2, 2);
                world.setBlock(i + 0, j + 2, k + 14, Blocks.stonebrick);
                world.setBlock(i + 0, j + 2, k + 15, Blocks.stonebrick);
                world.setBlock(i + 0, j + 2, k + 16, Blocks.stonebrick);
                world.setBlock(i + 0, j + 2, k + 17, Blocks.stonebrick);
                world.setBlock(i + 0, j + 3, k + 0, Blocks.stonebrick);
                world.setBlock(i + 0, j + 3, k + 1, Blocks.stonebrick);
                world.setBlock(i + 0, j + 3, k + 2, Blocks.stonebrick);
                world.setBlock(i + 0, j + 3, k + 3, Blocks.stonebrick);
                world.setBlock(i + 0, j + 3, k + 4, Blocks.stone_brick_stairs, 7, 2);
                world.setBlock(i + 0, j + 3, k + 5, Blocks.stone_brick_stairs, 6, 2);
                world.setBlock(i + 0, j + 3, k + 6, Blocks.stonebrick);
                world.setBlock(i + 0, j + 3, k + 7, Blocks.stonebrick);
                world.setBlock(i + 0, j + 3, k + 8, Blocks.stone_brick_stairs, 7, 2);
                world.setBlock(i + 0, j + 3, k + 9, Blocks.stone_brick_stairs, 6, 2);
                world.setBlock(i + 0, j + 3, k + 10, Blocks.stonebrick);
                world.setBlock(i + 0, j + 3, k + 11, Blocks.stonebrick);
                world.setBlock(i + 0, j + 3, k + 12, Blocks.stone_brick_stairs, 7, 2);
                world.setBlock(i + 0, j + 3, k + 13, Blocks.stone_brick_stairs, 6, 2);
                world.setBlock(i + 0, j + 3, k + 14, Blocks.stonebrick);
                world.setBlock(i + 0, j + 3, k + 15, Blocks.stonebrick);
                world.setBlock(i + 0, j + 3, k + 16, Blocks.stonebrick);
                world.setBlock(i + 0, j + 3, k + 17, Blocks.stonebrick);
                world.setBlock(i + 1, j + 0, k + 0, Blocks.planks);
                world.setBlock(i + 1, j + 0, k + 1, Blocks.stonebrick);
                world.setBlock(i + 1, j + 0, k + 2, Blocks.stonebrick);
                world.setBlock(i + 1, j + 0, k + 3, Blocks.stonebrick);
                world.setBlock(i + 1, j + 0, k + 4, Blocks.stonebrick);
                world.setBlock(i + 1, j + 0, k + 5, Blocks.stonebrick);
                world.setBlock(i + 1, j + 0, k + 6, Blocks.stonebrick);
                world.setBlock(i + 1, j + 0, k + 7, Blocks.stonebrick);
                world.setBlock(i + 1, j + 0, k + 8, Blocks.stonebrick);
                world.setBlock(i + 1, j + 0, k + 9, Blocks.stonebrick);
                world.setBlock(i + 1, j + 0, k + 10, Blocks.stonebrick);
                world.setBlock(i + 1, j + 0, k + 11, Blocks.stonebrick);
                world.setBlock(i + 1, j + 0, k + 12, Blocks.stonebrick);
                world.setBlock(i + 1, j + 0, k + 13, Blocks.stonebrick);
                world.setBlock(i + 1, j + 0, k + 14, Blocks.stonebrick);
                world.setBlock(i + 1, j + 0, k + 15, Blocks.stonebrick);
                world.setBlock(i + 1, j + 0, k + 16, Blocks.stonebrick);
                world.setBlock(i + 1, j + 0, k + 17, Blocks.planks);
                world.setBlock(i + 1, j + 1, k + 0, Blocks.stonebrick);
                world.setBlock(i + 1, j + 1, k + 17, Blocks.stonebrick);
                world.setBlock(i + 1, j + 2, k + 0, Blocks.stonebrick);
                world.setBlock(i + 1, j + 2, k + 17, Blocks.stonebrick);
                world.setBlock(i + 1, j + 3, k + 0, Blocks.stonebrick);
                world.setBlock(i + 1, j + 3, k + 17, Blocks.stonebrick);
                world.setBlock(i + 2, j + 0, k + 0, Blocks.planks);
                world.setBlock(i + 2, j + 0, k + 1, Blocks.stonebrick);
                world.setBlock(i + 2, j + 0, k + 2, Blocks.stonebrick);
                world.setBlock(i + 2, j + 0, k + 3, Blocks.stonebrick);
                world.setBlock(i + 2, j + 0, k + 4, Blocks.stonebrick);
                world.setBlock(i + 2, j + 0, k + 5, Blocks.stonebrick);
                world.setBlock(i + 2, j + 0, k + 6, Blocks.stonebrick);
                world.setBlock(i + 2, j + 0, k + 7, Blocks.stonebrick);
                world.setBlock(i + 2, j + 0, k + 8, Blocks.stonebrick);
                world.setBlock(i + 2, j + 0, k + 9, Blocks.stonebrick);
                world.setBlock(i + 2, j + 0, k + 10, Blocks.stonebrick);
                world.setBlock(i + 2, j + 0, k + 11, Blocks.stonebrick);
                world.setBlock(i + 2, j + 0, k + 12, Blocks.stonebrick);
                world.setBlock(i + 2, j + 0, k + 13, Blocks.stonebrick);
                world.setBlock(i + 2, j + 0, k + 14, Blocks.stonebrick);
                world.setBlock(i + 2, j + 0, k + 15, Blocks.stonebrick);
                world.setBlock(i + 2, j + 0, k + 16, Blocks.stonebrick);
                world.setBlock(i + 2, j + 0, k + 17, Blocks.planks);
                world.setBlock(i + 2, j + 1, k + 0, Blocks.stonebrick);
                world.setBlock(i + 2, j + 1, k + 17, Blocks.stonebrick);
                world.setBlock(i + 2, j + 2, k + 0, Blocks.stonebrick);
                world.setBlock(i + 2, j + 2, k + 17, Blocks.stonebrick);
                world.setBlock(i + 2, j + 3, k + 0, Blocks.stonebrick);
                world.setBlock(i + 2, j + 3, k + 17, Blocks.stonebrick);
                world.setBlock(i + 3, j + 0, k + 0, Blocks.planks);
                world.setBlock(i + 3, j + 0, k + 1, Blocks.stonebrick);
                world.setBlock(i + 3, j + 0, k + 2, Blocks.stonebrick);
                world.setBlock(i + 3, j + 0, k + 3, Blocks.stonebrick);
                world.setBlock(i + 3, j + 0, k + 4, Blocks.stonebrick);
                world.setBlock(i + 3, j + 0, k + 5, Blocks.stonebrick);
                world.setBlock(i + 3, j + 0, k + 6, Blocks.stonebrick);
                world.setBlock(i + 3, j + 0, k + 7, Blocks.stonebrick);
                world.setBlock(i + 3, j + 0, k + 8, Blocks.stonebrick);
                world.setBlock(i + 3, j + 0, k + 9, Blocks.stonebrick);
                world.setBlock(i + 3, j + 0, k + 10, Blocks.stonebrick);
                world.setBlock(i + 3, j + 0, k + 11, Blocks.stonebrick);
                world.setBlock(i + 3, j + 0, k + 12, Blocks.stonebrick);
                world.setBlock(i + 3, j + 0, k + 13, Blocks.stonebrick);
                world.setBlock(i + 3, j + 0, k + 14, Blocks.stonebrick);
                world.setBlock(i + 3, j + 0, k + 15, Blocks.stonebrick);
                world.setBlock(i + 3, j + 0, k + 16, Blocks.stonebrick);
                world.setBlock(i + 3, j + 0, k + 17, Blocks.planks);
                world.setBlock(i + 3, j + 1, k + 0, Blocks.stonebrick);
                world.setBlock(i + 3, j + 1, k + 4, Blocks.stone_brick_stairs);
                world.setBlock(i + 3, j + 1, k + 13, Blocks.stone_brick_stairs);
                world.setBlock(i + 3, j + 1, k + 17, Blocks.stonebrick);
                world.setBlock(i + 3, j + 2, k + 0, Blocks.stone_brick_stairs, 1, 2);
                world.setBlock(i + 3, j + 2, k + 17, Blocks.stone_brick_stairs, 1, 2);
                world.setBlock(i + 3, j + 3, k + 0, Blocks.stone_brick_stairs, 5, 2);
                world.setBlock(i + 3, j + 3, k + 17, Blocks.stone_brick_stairs, 5, 2);
                world.setBlock(i + 3, j + 4, k + 13, Blocks.stone_brick_stairs, 4, 2);
                world.setBlock(i + 4, j + 0, k + 0, Blocks.planks);
                world.setBlock(i + 4, j + 0, k + 1, Blocks.stonebrick);
                world.setBlock(i + 4, j + 0, k + 2, Blocks.stonebrick);
                world.setBlock(i + 4, j + 0, k + 3, Blocks.stonebrick);
                world.setBlock(i + 4, j + 0, k + 4, Blocks.stonebrick);
                world.setBlock(i + 4, j + 0, k + 5, Blocks.planks);
                world.setBlock(i + 4, j + 0, k + 6, Blocks.planks);
                world.setBlock(i + 4, j + 0, k + 7, Blocks.planks);
                world.setBlock(i + 4, j + 0, k + 8, Blocks.planks);
                world.setBlock(i + 4, j + 0, k + 9, Blocks.planks);
                world.setBlock(i + 4, j + 0, k + 10, Blocks.planks);
                world.setBlock(i + 4, j + 0, k + 11, Blocks.planks);
                world.setBlock(i + 4, j + 0, k + 12, Blocks.planks);
                world.setBlock(i + 4, j + 0, k + 13, Blocks.stonebrick);
                world.setBlock(i + 4, j + 0, k + 14, Blocks.stonebrick);
                world.setBlock(i + 4, j + 0, k + 15, Blocks.stonebrick);
                world.setBlock(i + 4, j + 0, k + 16, Blocks.stonebrick);
                world.setBlock(i + 4, j + 0, k + 17, Blocks.planks);
                world.setBlock(i + 4, j + 1, k + 0, Blocks.stonebrick);
                world.setBlock(i + 4, j + 1, k + 3, Blocks.stone_brick_stairs, 2, 2);
                world.setBlock(i + 4, j + 1, k + 4, Blocks.stonebrick);
                world.setBlock(i + 4, j + 1, k + 13, Blocks.stonebrick);
                world.setBlock(i + 4, j + 1, k + 14, Blocks.stone_brick_stairs, 3, 2);
                world.setBlock(i + 4, j + 1, k + 17, Blocks.stonebrick);
                world.setBlock(i + 4, j + 2, k + 0, Blocks.stone_brick_stairs);
                world.setBlock(i + 4, j + 2, k + 4, Blocks.stonebrick);
                world.setBlock(i + 4, j + 2, k + 13, Blocks.stonebrick);
                world.setBlock(i + 4, j + 2, k + 17, Blocks.stone_brick_stairs);
                world.setBlock(i + 4, j + 3, k + 0, Blocks.stone_brick_stairs, 4, 2);
                world.setBlock(i + 4, j + 3, k + 4, Blocks.stonebrick);
                world.setBlock(i + 4, j + 3, k + 13, Blocks.stonebrick);
                world.setBlock(i + 4, j + 3, k + 17, Blocks.stone_brick_stairs, 4, 2);
                world.setBlock(i + 4, j + 4, k + 4, Blocks.stonebrick);
                world.setBlock(i + 4, j + 4, k + 5, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 4, j + 4, k + 6, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 4, j + 4, k + 7, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 4, j + 4, k + 8, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 4, j + 4, k + 9, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 4, j + 4, k + 10, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 4, j + 4, k + 11, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 4, j + 4, k + 12, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 4, j + 4, k + 13, Blocks.stonebrick);
                world.setBlock(i + 4, j + 4, k + 14, Blocks.stone_brick_stairs, 7, 2);
                world.setBlock(i + 4, j + 5, k + 4, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 4, j + 5, k + 5, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 4, j + 5, k + 12, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 4, j + 5, k + 13, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 5, j + 0, k + 0, Blocks.planks);
                world.setBlock(i + 5, j + 0, k + 1, Blocks.stonebrick);
                world.setBlock(i + 5, j + 0, k + 2, Blocks.stonebrick);
                world.setBlock(i + 5, j + 0, k + 3, Blocks.stonebrick);
                world.setBlock(i + 5, j + 0, k + 4, Blocks.planks);
                world.setBlock(i + 5, j + 0, k + 5, Blocks.glowstone);
                world.setBlock(i + 5, j + 0, k + 6, Blocks.wool, 8, 2);
                world.setBlock(i + 5, j + 0, k + 7, Blocks.wool, 8, 2);
                world.setBlock(i + 5, j + 0, k + 8, Blocks.wool, 8, 2);
                world.setBlock(i + 5, j + 0, k + 9, Blocks.wool, 8, 2);
                world.setBlock(i + 5, j + 0, k + 10, Blocks.wool, 8, 2);
                world.setBlock(i + 5, j + 0, k + 11, Blocks.wool, 8, 2);
                world.setBlock(i + 5, j + 0, k + 12, Blocks.glowstone);
                world.setBlock(i + 5, j + 0, k + 13, Blocks.planks);
                world.setBlock(i + 5, j + 0, k + 14, Blocks.stonebrick);
                world.setBlock(i + 5, j + 0, k + 15, Blocks.stonebrick);
                world.setBlock(i + 5, j + 0, k + 16, Blocks.stonebrick);
                world.setBlock(i + 5, j + 0, k + 17, Blocks.planks);
                world.setBlock(i + 5, j + 1, k + 0, Blocks.stone_brick_stairs, 5, 2);
                world.setBlock(i + 5, j + 1, k + 17, Blocks.stone_brick_stairs, 5, 2);
                world.setBlock(i + 5, j + 2, k + 0, Blocks.stonebrick);
                world.setBlock(i + 5, j + 2, k + 17, Blocks.stonebrick);
                world.setBlock(i + 5, j + 3, k + 0, Blocks.stonebrick);
                world.setBlock(i + 5, j + 3, k + 17, Blocks.stonebrick);
                world.setBlock(i + 5, j + 4, k + 4, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 5, j + 4, k + 13, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 5, j + 5, k + 4, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 5, j + 5, k + 5, Blocks.double_stone_slab, 5, 2);
                world.setBlock(i + 5, j + 5, k + 6, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 5, j + 5, k + 7, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 5, j + 5, k + 8, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 5, j + 5, k + 9, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 5, j + 5, k + 10, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 5, j + 5, k + 11, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 5, j + 5, k + 12, Blocks.double_stone_slab, 5, 2);
                world.setBlock(i + 5, j + 5, k + 13, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 6, j + 0, k + 0, Blocks.planks);
                world.setBlock(i + 6, j + 0, k + 1, Blocks.stonebrick);
                world.setBlock(i + 6, j + 0, k + 2, Blocks.stonebrick);
                world.setBlock(i + 6, j + 0, k + 3, Blocks.stonebrick);
                world.setBlock(i + 6, j + 0, k + 4, Blocks.planks);
                world.setBlock(i + 6, j + 0, k + 5, Blocks.wool, 8, 2);
                world.setBlock(i + 6, j + 0, k + 6, Blocks.wool, 8, 2);
                world.setBlock(i + 6, j + 0, k + 7, Blocks.wool, 8, 2);
                world.setBlock(i + 6, j + 0, k + 8, Blocks.wool, 8, 2);
                world.setBlock(i + 6, j + 0, k + 9, Blocks.wool, 8, 2);
                world.setBlock(i + 6, j + 0, k + 10, Blocks.wool, 8, 2);
                world.setBlock(i + 6, j + 0, k + 11, Blocks.wool, 8, 2);
                world.setBlock(i + 6, j + 0, k + 12, Blocks.wool, 8, 2);
                world.setBlock(i + 6, j + 0, k + 13, Blocks.planks);
                world.setBlock(i + 6, j + 0, k + 14, Blocks.stonebrick);
                world.setBlock(i + 6, j + 0, k + 15, Blocks.stonebrick);
                world.setBlock(i + 6, j + 0, k + 16, Blocks.stonebrick);
                world.setBlock(i + 6, j + 0, k + 17, Blocks.planks);
                world.setBlock(i + 6, j + 2, k + 0, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 6, j + 2, k + 17, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 6, j + 3, k + 0, Blocks.stonebrick);
                world.setBlock(i + 6, j + 3, k + 17, Blocks.stonebrick);
                world.setBlock(i + 6, j + 4, k + 4, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 6, j + 4, k + 13, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 6, j + 5, k + 5, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 6, j + 5, k + 6, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 6, j + 5, k + 7, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 6, j + 5, k + 8, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 6, j + 5, k + 9, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 6, j + 5, k + 10, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 6, j + 5, k + 11, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 6, j + 5, k + 12, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 6, j + 6, k + 6, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 6, j + 6, k + 11, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 7, j + 0, k + 0, Blocks.planks);
                world.setBlock(i + 7, j + 0, k + 1, Blocks.stonebrick);
                world.setBlock(i + 7, j + 0, k + 2, Blocks.stonebrick);
                world.setBlock(i + 7, j + 0, k + 3, Blocks.stonebrick);
                world.setBlock(i + 7, j + 0, k + 4, Blocks.planks);
                world.setBlock(i + 7, j + 0, k + 5, Blocks.wool, 8, 2);
                world.setBlock(i + 7, j + 0, k + 6, Blocks.wool, 8, 2);
                world.setBlock(i + 7, j + 0, k + 7, Blocks.wool, 8, 2);
                world.setBlock(i + 7, j + 0, k + 8, Blocks.wool, 8, 2);
                world.setBlock(i + 7, j + 0, k + 9, Blocks.wool, 8, 2);
                world.setBlock(i + 7, j + 0, k + 10, Blocks.wool, 8, 2);
                world.setBlock(i + 7, j + 0, k + 11, Blocks.wool, 8, 2);
                world.setBlock(i + 7, j + 0, k + 12, Blocks.wool, 8, 2);
                world.setBlock(i + 7, j + 0, k + 13, Blocks.planks);
                world.setBlock(i + 7, j + 0, k + 14, Blocks.stonebrick);
                world.setBlock(i + 7, j + 0, k + 15, Blocks.stonebrick);
                world.setBlock(i + 7, j + 0, k + 16, Blocks.stonebrick);
                world.setBlock(i + 7, j + 0, k + 17, Blocks.planks);
                world.setBlock(i + 7, j + 3, k + 0, Blocks.stone_brick_stairs, 5, 2);
                world.setBlock(i + 7, j + 3, k + 17, Blocks.stone_brick_stairs, 5, 2);
                world.setBlock(i + 7, j + 4, k + 4, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 7, j + 4, k + 13, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 7, j + 5, k + 5, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 7, j + 5, k + 6, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 7, j + 5, k + 11, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 7, j + 5, k + 12, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 8, j + 0, k + 0, Blocks.planks);
                world.setBlock(i + 8, j + 0, k + 1, Blocks.stonebrick);
                world.setBlock(i + 8, j + 0, k + 2, Blocks.stonebrick);
                world.setBlock(i + 8, j + 0, k + 3, Blocks.stonebrick);
                world.setBlock(i + 8, j + 0, k + 4, Blocks.planks);
                world.setBlock(i + 8, j + 0, k + 5, Blocks.wool, 8, 2);
                world.setBlock(i + 8, j + 0, k + 6, Blocks.wool, 8, 2);
                world.setBlock(i + 8, j + 0, k + 7, Blocks.wool, 8, 2);
                world.setBlock(i + 8, j + 0, k + 8, Blocks.wool, 8, 2);
                world.setBlock(i + 8, j + 0, k + 9, Blocks.wool, 8, 2);
                world.setBlock(i + 8, j + 0, k + 10, Blocks.wool, 8, 2);
                world.setBlock(i + 8, j + 0, k + 11, Blocks.wool, 8, 2);
                world.setBlock(i + 8, j + 0, k + 12, Blocks.wool, 8, 2);
                world.setBlock(i + 8, j + 0, k + 13, Blocks.planks);
                world.setBlock(i + 8, j + 0, k + 14, Blocks.stonebrick);
                world.setBlock(i + 8, j + 0, k + 15, Blocks.stonebrick);
                world.setBlock(i + 8, j + 0, k + 16, Blocks.stonebrick);
                world.setBlock(i + 8, j + 0, k + 17, Blocks.planks);
                world.setBlock(i + 8, j + 3, k + 0, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 8, j + 3, k + 17, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 8, j + 4, k + 4, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 8, j + 4, k + 13, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 8, j + 5, k + 5, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 8, j + 5, k + 6, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 8, j + 5, k + 11, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 8, j + 5, k + 12, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 9, j + 0, k + 0, Blocks.planks);
                world.setBlock(i + 9, j + 0, k + 1, Blocks.stonebrick);
                world.setBlock(i + 9, j + 0, k + 2, Blocks.stonebrick);
                world.setBlock(i + 9, j + 0, k + 3, Blocks.stonebrick);
                world.setBlock(i + 9, j + 0, k + 4, Blocks.planks);
                world.setBlock(i + 9, j + 0, k + 5, Blocks.wool, 8, 2);
                world.setBlock(i + 9, j + 0, k + 6, Blocks.wool, 8, 2);
                world.setBlock(i + 9, j + 0, k + 7, Blocks.wool, 8, 2);
                world.setBlock(i + 9, j + 0, k + 8, Blocks.wool, 8, 2);
                world.setBlock(i + 9, j + 0, k + 9, Blocks.wool, 8, 2);
                world.setBlock(i + 9, j + 0, k + 10, Blocks.wool, 8, 2);
                world.setBlock(i + 9, j + 0, k + 11, Blocks.wool, 8, 2);
                world.setBlock(i + 9, j + 0, k + 12, Blocks.wool, 8, 2);
                world.setBlock(i + 9, j + 0, k + 13, Blocks.planks);
                world.setBlock(i + 9, j + 0, k + 14, Blocks.stonebrick);
                world.setBlock(i + 9, j + 0, k + 15, Blocks.stonebrick);
                world.setBlock(i + 9, j + 0, k + 16, Blocks.stonebrick);
                world.setBlock(i + 9, j + 0, k + 17, Blocks.planks);
                world.setBlock(i + 9, j + 1, k + 8, Blocks.chest, 5, 2);
                world.setBlock(i + 9, j + 1, k + 9, Blocks.chest, 5, 2);
                world.setBlock(i + 9, j + 3, k + 0, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 9, j + 3, k + 17, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 9, j + 4, k + 4, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 9, j + 4, k + 13, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 9, j + 5, k + 5, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 9, j + 5, k + 6, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 9, j + 5, k + 11, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 9, j + 5, k + 12, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 10, j + 0, k + 0, Blocks.planks);
                world.setBlock(i + 10, j + 0, k + 1, Blocks.stonebrick);
                world.setBlock(i + 10, j + 0, k + 2, Blocks.stonebrick);
                world.setBlock(i + 10, j + 0, k + 3, Blocks.stonebrick);
                world.setBlock(i + 10, j + 0, k + 4, Blocks.planks);
                world.setBlock(i + 10, j + 0, k + 5, Blocks.wool, 8, 2);
                world.setBlock(i + 10, j + 0, k + 6, Blocks.wool, 8, 2);
                world.setBlock(i + 10, j + 0, k + 7, Blocks.wool, 8, 2);
                world.setBlock(i + 10, j + 0, k + 8, Blocks.wool, 8, 2);
                world.setBlock(i + 10, j + 0, k + 9, Blocks.wool, 8, 2);
                world.setBlock(i + 10, j + 0, k + 10, Blocks.wool, 8, 2);
                world.setBlock(i + 10, j + 0, k + 11, Blocks.wool, 8, 2);
                world.setBlock(i + 10, j + 0, k + 12, Blocks.wool, 8, 2);
                world.setBlock(i + 10, j + 0, k + 13, Blocks.planks);
                world.setBlock(i + 10, j + 0, k + 14, Blocks.stonebrick);
                world.setBlock(i + 10, j + 0, k + 15, Blocks.stonebrick);
                world.setBlock(i + 10, j + 0, k + 16, Blocks.stonebrick);
                world.setBlock(i + 10, j + 0, k + 17, Blocks.planks);
                world.setBlock(i + 10, j + 3, k + 0, Blocks.stone_brick_stairs, 4, 2);
                world.setBlock(i + 10, j + 3, k + 17, Blocks.stone_brick_stairs, 4, 2);
                world.setBlock(i + 10, j + 4, k + 4, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 10, j + 4, k + 13, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 10, j + 5, k + 5, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 10, j + 5, k + 6, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 10, j + 5, k + 11, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 10, j + 5, k + 12, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 11, j + 0, k + 0, Blocks.planks);
                world.setBlock(i + 11, j + 0, k + 1, Blocks.stonebrick);
                world.setBlock(i + 11, j + 0, k + 2, Blocks.stonebrick);
                world.setBlock(i + 11, j + 0, k + 3, Blocks.stonebrick);
                world.setBlock(i + 11, j + 0, k + 4, Blocks.planks);
                world.setBlock(i + 11, j + 0, k + 5, Blocks.wool, 8, 2);
                world.setBlock(i + 11, j + 0, k + 6, Blocks.wool, 8, 2);
                world.setBlock(i + 11, j + 0, k + 7, Blocks.wool, 8, 2);
                world.setBlock(i + 11, j + 0, k + 8, Blocks.wool, 8, 2);
                world.setBlock(i + 11, j + 0, k + 9, Blocks.wool, 8, 2);
                world.setBlock(i + 11, j + 0, k + 10, Blocks.wool, 8, 2);
                world.setBlock(i + 11, j + 0, k + 11, Blocks.wool, 8, 2);
                world.setBlock(i + 11, j + 0, k + 12, Blocks.wool, 8, 2);
                world.setBlock(i + 11, j + 0, k + 13, Blocks.planks);
                world.setBlock(i + 11, j + 0, k + 14, Blocks.stonebrick);
                world.setBlock(i + 11, j + 0, k + 15, Blocks.stonebrick);
                world.setBlock(i + 11, j + 0, k + 16, Blocks.stonebrick);
                world.setBlock(i + 11, j + 0, k + 17, Blocks.planks);
                world.setBlock(i + 11, j + 2, k + 0, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 11, j + 2, k + 17, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 11, j + 3, k + 0, Blocks.stonebrick);
                world.setBlock(i + 11, j + 3, k + 17, Blocks.stonebrick);
                world.setBlock(i + 11, j + 4, k + 4, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 11, j + 4, k + 13, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 11, j + 5, k + 5, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 11, j + 5, k + 6, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 11, j + 5, k + 11, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 11, j + 5, k + 12, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 12, j + 0, k + 0, Blocks.planks);
                world.setBlock(i + 12, j + 0, k + 1, Blocks.stonebrick);
                world.setBlock(i + 12, j + 0, k + 2, Blocks.stonebrick);
                world.setBlock(i + 12, j + 0, k + 3, Blocks.stonebrick);
                world.setBlock(i + 12, j + 0, k + 4, Blocks.planks);
                world.setBlock(i + 12, j + 0, k + 5, Blocks.wool, 8, 2);
                world.setBlock(i + 12, j + 0, k + 6, Blocks.wool, 8, 2);
                world.setBlock(i + 12, j + 0, k + 7, Blocks.wool, 8, 2);
                world.setBlock(i + 12, j + 0, k + 8, Blocks.wool, 8, 2);
                world.setBlock(i + 12, j + 0, k + 9, Blocks.wool, 8, 2);
                world.setBlock(i + 12, j + 0, k + 10, Blocks.wool, 8, 2);
                world.setBlock(i + 12, j + 0, k + 11, Blocks.wool, 8, 2);
                world.setBlock(i + 12, j + 0, k + 12, Blocks.wool, 8, 2);
                world.setBlock(i + 12, j + 0, k + 13, Blocks.planks);
                world.setBlock(i + 12, j + 0, k + 14, Blocks.stonebrick);
                world.setBlock(i + 12, j + 0, k + 15, Blocks.stonebrick);
                world.setBlock(i + 12, j + 0, k + 16, Blocks.stonebrick);
                world.setBlock(i + 12, j + 0, k + 17, Blocks.planks);
                world.setBlock(i + 12, j + 1, k + 0, Blocks.stone_brick_stairs, 4, 2);
                world.setBlock(i + 12, j + 1, k + 17, Blocks.stone_brick_stairs, 4, 2);
                world.setBlock(i + 12, j + 2, k + 0, Blocks.stonebrick);
                world.setBlock(i + 12, j + 2, k + 17, Blocks.stonebrick);
                world.setBlock(i + 12, j + 3, k + 0, Blocks.stonebrick);
                world.setBlock(i + 12, j + 3, k + 17, Blocks.stonebrick);
                world.setBlock(i + 12, j + 4, k + 4, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 12, j + 4, k + 13, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 12, j + 5, k + 5, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 12, j + 5, k + 6, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 12, j + 5, k + 7, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 12, j + 5, k + 8, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 12, j + 5, k + 9, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 12, j + 5, k + 10, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 12, j + 5, k + 11, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 12, j + 5, k + 12, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 12, j + 6, k + 6, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 12, j + 6, k + 11, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 13, j + 0, k + 0, Blocks.planks);
                world.setBlock(i + 13, j + 0, k + 1, Blocks.stonebrick);
                world.setBlock(i + 13, j + 0, k + 2, Blocks.stonebrick);
                world.setBlock(i + 13, j + 0, k + 3, Blocks.stonebrick);
                world.setBlock(i + 13, j + 0, k + 4, Blocks.planks);
                world.setBlock(i + 13, j + 0, k + 5, Blocks.glowstone);
                world.setBlock(i + 13, j + 0, k + 6, Blocks.wool, 8, 2);
                world.setBlock(i + 13, j + 0, k + 7, Blocks.wool, 8, 2);
                world.setBlock(i + 13, j + 0, k + 8, Blocks.wool, 8, 2);
                world.setBlock(i + 13, j + 0, k + 9, Blocks.wool, 8, 2);
                world.setBlock(i + 13, j + 0, k + 10, Blocks.wool, 8, 2);
                world.setBlock(i + 13, j + 0, k + 11, Blocks.wool, 8, 2);
                world.setBlock(i + 13, j + 0, k + 12, Blocks.glowstone);
                world.setBlock(i + 13, j + 0, k + 13, Blocks.planks);
                world.setBlock(i + 13, j + 0, k + 14, Blocks.stonebrick);
                world.setBlock(i + 13, j + 0, k + 15, Blocks.stonebrick);
                world.setBlock(i + 13, j + 0, k + 16, Blocks.stonebrick);
                world.setBlock(i + 13, j + 0, k + 17, Blocks.planks);
                world.setBlock(i + 13, j + 1, k + 0, Blocks.stonebrick);
                world.setBlock(i + 13, j + 1, k + 17, Blocks.stonebrick);
                world.setBlock(i + 13, j + 2, k + 0, Blocks.stone_brick_stairs, 1, 2);
                world.setBlock(i + 13, j + 2, k + 17, Blocks.stone_brick_stairs, 1, 2);
                world.setBlock(i + 13, j + 3, k + 0, Blocks.stone_brick_stairs, 5, 2);
                world.setBlock(i + 13, j + 3, k + 17, Blocks.stone_brick_stairs, 5, 2);
                world.setBlock(i + 13, j + 4, k + 4, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 13, j + 4, k + 13, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 13, j + 5, k + 4, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 13, j + 5, k + 5, Blocks.double_stone_slab, 5, 2);
                world.setBlock(i + 13, j + 5, k + 6, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 13, j + 5, k + 7, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 13, j + 5, k + 8, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 13, j + 5, k + 9, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 13, j + 5, k + 10, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 13, j + 5, k + 11, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 13, j + 5, k + 12, Blocks.double_stone_slab, 5, 2);
                world.setBlock(i + 13, j + 5, k + 13, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 14, j + 0, k + 0, Blocks.planks);
                world.setBlock(i + 14, j + 0, k + 1, Blocks.stonebrick);
                world.setBlock(i + 14, j + 0, k + 2, Blocks.stonebrick);
                world.setBlock(i + 14, j + 0, k + 4, Blocks.planks);
                world.setBlock(i + 14, j + 0, k + 5, Blocks.planks);
                world.setBlock(i + 14, j + 0, k + 6, Blocks.planks);
                world.setBlock(i + 14, j + 0, k + 7, Blocks.planks);
                world.setBlock(i + 14, j + 0, k + 8, Blocks.planks);
                world.setBlock(i + 14, j + 0, k + 9, Blocks.planks);
                world.setBlock(i + 14, j + 0, k + 10, Blocks.planks);
                world.setBlock(i + 14, j + 0, k + 11, Blocks.planks);
                world.setBlock(i + 14, j + 0, k + 12, Blocks.planks);
                world.setBlock(i + 14, j + 0, k + 13, Blocks.stonebrick);
                world.setBlock(i + 14, j + 0, k + 14, Blocks.stonebrick);
                world.setBlock(i + 14, j + 0, k + 15, Blocks.stonebrick);
                world.setBlock(i + 14, j + 0, k + 16, Blocks.stonebrick);
                world.setBlock(i + 14, j + 0, k + 17, Blocks.planks);
                world.setBlock(i + 14, j + 1, k + 0, Blocks.stonebrick);
                world.setBlock(i + 14, j + 1, k + 3, Blocks.stone_brick_stairs, 2, 2);
                world.setBlock(i + 14, j + 1, k + 4, Blocks.stonebrick);
                world.setBlock(i + 14, j + 1, k + 13, Blocks.stonebrick);
                world.setBlock(i + 14, j + 1, k + 14, Blocks.stone_brick_stairs, 3, 2);
                world.setBlock(i + 14, j + 1, k + 17, Blocks.stonebrick);
                world.setBlock(i + 14, j + 2, k + 0, Blocks.stone_brick_stairs);
                world.setBlock(i + 14, j + 2, k + 4, Blocks.stonebrick);
                world.setBlock(i + 14, j + 2, k + 13, Blocks.stonebrick);
                world.setBlock(i + 14, j + 2, k + 17, Blocks.stone_brick_stairs);
                world.setBlock(i + 14, j + 3, k + 0, Blocks.stone_brick_stairs, 4, 2);
                world.setBlock(i + 14, j + 3, k + 4, Blocks.stonebrick);
                world.setBlock(i + 14, j + 3, k + 13, Blocks.stonebrick);
                world.setBlock(i + 14, j + 3, k + 17, Blocks.stone_brick_stairs, 4, 2);
                world.setBlock(i + 14, j + 4, k + 3, Blocks.stone_brick_stairs, 6, 2);
                world.setBlock(i + 14, j + 4, k + 4, Blocks.stonebrick);
                world.setBlock(i + 14, j + 4, k + 5, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 14, j + 4, k + 6, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 14, j + 4, k + 7, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 14, j + 4, k + 8, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 14, j + 4, k + 9, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 14, j + 4, k + 10, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 14, j + 4, k + 11, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 14, j + 4, k + 12, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 14, j + 4, k + 13, Blocks.stonebrick);
                world.setBlock(i + 14, j + 4, k + 14, Blocks.stone_brick_stairs, 7, 2);
                world.setBlock(i + 14, j + 5, k + 4, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 14, j + 5, k + 5, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 14, j + 5, k + 12, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 14, j + 5, k + 13, Blocks.stone_slab, 5, 2);
                world.setBlock(i + 15, j + 0, k + 0, Blocks.planks);
                world.setBlock(i + 15, j + 0, k + 1, Blocks.stonebrick);
                world.setBlock(i + 15, j + 0, k + 2, Blocks.stonebrick);
                world.setBlock(i + 15, j + 0, k + 3, Blocks.stonebrick);
                world.setBlock(i + 15, j + 0, k + 4, Blocks.planks);
                world.setBlock(i + 15, j + 0, k + 5, Blocks.stonebrick);
                world.setBlock(i + 15, j + 0, k + 6, Blocks.stonebrick);
                world.setBlock(i + 15, j + 0, k + 7, Blocks.stonebrick);
                world.setBlock(i + 15, j + 0, k + 8, Blocks.stonebrick);
                world.setBlock(i + 15, j + 0, k + 9, Blocks.stonebrick);
                world.setBlock(i + 15, j + 0, k + 10, Blocks.stonebrick);
                world.setBlock(i + 15, j + 0, k + 11, Blocks.stonebrick);
                world.setBlock(i + 15, j + 0, k + 12, Blocks.stonebrick);
                world.setBlock(i + 15, j + 0, k + 13, Blocks.stonebrick);
                world.setBlock(i + 15, j + 0, k + 14, Blocks.stonebrick);
                world.setBlock(i + 15, j + 0, k + 15, Blocks.stonebrick);
                world.setBlock(i + 15, j + 0, k + 16, Blocks.stonebrick);
                world.setBlock(i + 15, j + 0, k + 17, Blocks.planks);
                world.setBlock(i + 15, j + 1, k + 0, Blocks.stonebrick);
                world.setBlock(i + 15, j + 1, k + 4, Blocks.stone_brick_stairs, 1, 2);
                world.setBlock(i + 15, j + 1, k + 13, Blocks.stone_brick_stairs, 1, 2);
                world.setBlock(i + 15, j + 1, k + 17, Blocks.stonebrick);
                world.setBlock(i + 15, j + 2, k + 0, Blocks.stonebrick);
                world.setBlock(i + 15, j + 2, k + 17, Blocks.stonebrick);
                world.setBlock(i + 15, j + 3, k + 0, Blocks.stonebrick);
                world.setBlock(i + 15, j + 3, k + 17, Blocks.stonebrick);
                world.setBlock(i + 15, j + 4, k + 4, Blocks.stone_brick_stairs, 5, 2);
                world.setBlock(i + 15, j + 4, k + 13, Blocks.stone_brick_stairs, 5, 2);
                world.setBlock(i + 16, j + 0, k + 0, Blocks.planks);
                world.setBlock(i + 16, j + 0, k + 1, Blocks.stonebrick);
                world.setBlock(i + 16, j + 0, k + 2, Blocks.stonebrick);
                world.setBlock(i + 16, j + 0, k + 3, Blocks.stonebrick);
                world.setBlock(i + 16, j + 0, k + 4, Blocks.stonebrick);
                world.setBlock(i + 16, j + 0, k + 5, Blocks.stonebrick);
                world.setBlock(i + 16, j + 0, k + 6, Blocks.stonebrick);
                world.setBlock(i + 16, j + 0, k + 7, Blocks.stonebrick);
                world.setBlock(i + 16, j + 0, k + 8, Blocks.stonebrick);
                world.setBlock(i + 16, j + 0, k + 9, Blocks.stonebrick);
                world.setBlock(i + 16, j + 0, k + 10, Blocks.stonebrick);
                world.setBlock(i + 16, j + 0, k + 11, Blocks.stonebrick);
                world.setBlock(i + 16, j + 0, k + 12, Blocks.stonebrick);
                world.setBlock(i + 16, j + 0, k + 13, Blocks.stonebrick);
                world.setBlock(i + 16, j + 0, k + 14, Blocks.stonebrick);
                world.setBlock(i + 16, j + 0, k + 15, Blocks.stonebrick);
                world.setBlock(i + 16, j + 0, k + 16, Blocks.stonebrick);
                world.setBlock(i + 16, j + 0, k + 17, Blocks.planks);
                world.setBlock(i + 16, j + 1, k + 0, Blocks.stonebrick);
                world.setBlock(i + 16, j + 1, k + 17, Blocks.stonebrick);
                world.setBlock(i + 16, j + 2, k + 0, Blocks.stonebrick);
                world.setBlock(i + 16, j + 2, k + 17, Blocks.stonebrick);
                world.setBlock(i + 16, j + 3, k + 0, Blocks.stonebrick);
                world.setBlock(i + 16, j + 3, k + 17, Blocks.stonebrick);
                world.setBlock(i + 17, j + 0, k + 0, Blocks.planks);
                world.setBlock(i + 17, j + 0, k + 1, Blocks.stonebrick);
                world.setBlock(i + 17, j + 0, k + 2, Blocks.stonebrick);
                world.setBlock(i + 17, j + 0, k + 3, Blocks.stonebrick);
                world.setBlock(i + 17, j + 0, k + 4, Blocks.stonebrick);
                world.setBlock(i + 17, j + 0, k + 5, Blocks.stonebrick);
                world.setBlock(i + 17, j + 0, k + 6, Blocks.stonebrick);
                world.setBlock(i + 17, j + 0, k + 7, Blocks.stonebrick);
                world.setBlock(i + 17, j + 0, k + 8, Blocks.stonebrick);
                world.setBlock(i + 17, j + 0, k + 9, Blocks.stonebrick);
                world.setBlock(i + 17, j + 0, k + 10, Blocks.stonebrick);
                world.setBlock(i + 17, j + 0, k + 11, Blocks.stonebrick);
                world.setBlock(i + 17, j + 0, k + 12, Blocks.stonebrick);
                world.setBlock(i + 17, j + 0, k + 13, Blocks.stonebrick);
                world.setBlock(i + 17, j + 0, k + 14, Blocks.stonebrick);
                world.setBlock(i + 17, j + 0, k + 15, Blocks.stonebrick);
                world.setBlock(i + 17, j + 0, k + 16, Blocks.stonebrick);
                world.setBlock(i + 17, j + 0, k + 17, Blocks.planks);
                world.setBlock(i + 17, j + 1, k + 0, Blocks.stonebrick);
                world.setBlock(i + 17, j + 1, k + 17, Blocks.stonebrick);
                world.setBlock(i + 17, j + 2, k + 0, Blocks.stonebrick);
                world.setBlock(i + 17, j + 2, k + 17, Blocks.stonebrick);
                world.setBlock(i + 17, j + 3, k + 0, Blocks.stonebrick);
                world.setBlock(i + 17, j + 3, k + 17, Blocks.stonebrick);
                world.setBlock(i + 18, j + 0, k + 0, Blocks.planks);
                world.setBlock(i + 18, j + 0, k + 1, Blocks.planks);
                world.setBlock(i + 18, j + 0, k + 2, Blocks.planks);
                world.setBlock(i + 18, j + 0, k + 3, Blocks.planks);
                world.setBlock(i + 18, j + 0, k + 4, Blocks.planks);
                world.setBlock(i + 18, j + 0, k + 5, Blocks.planks);
                world.setBlock(i + 18, j + 0, k + 6, Blocks.planks);
                world.setBlock(i + 18, j + 0, k + 7, Blocks.planks);
                world.setBlock(i + 18, j + 0, k + 8, Blocks.planks);
                world.setBlock(i + 18, j + 0, k + 9, Blocks.planks);
                world.setBlock(i + 18, j + 0, k + 10, Blocks.planks);
                world.setBlock(i + 18, j + 0, k + 11, Blocks.planks);
                world.setBlock(i + 18, j + 0, k + 12, Blocks.planks);
                world.setBlock(i + 18, j + 0, k + 13, Blocks.planks);
                world.setBlock(i + 18, j + 0, k + 14, Blocks.planks);
                world.setBlock(i + 18, j + 0, k + 15, Blocks.planks);
                world.setBlock(i + 18, j + 0, k + 16, Blocks.planks);
                world.setBlock(i + 18, j + 0, k + 17, Blocks.planks);
                world.setBlock(i + 18, j + 1, k + 0, Blocks.stonebrick);
                world.setBlock(i + 18, j + 1, k + 1, Blocks.stonebrick);
                world.setBlock(i + 18, j + 1, k + 2, Blocks.stonebrick);
                world.setBlock(i + 18, j + 1, k + 3, Blocks.stonebrick);
                world.setBlock(i + 18, j + 1, k + 4, Blocks.stonebrick);
                world.setBlock(i + 18, j + 1, k + 5, Blocks.stonebrick);
                world.setBlock(i + 18, j + 1, k + 6, Blocks.stone_brick_stairs, 7, 2);
                world.setBlock(i + 18, j + 1, k + 11, Blocks.stone_brick_stairs, 6, 2);
                world.setBlock(i + 18, j + 1, k + 12, Blocks.stonebrick);
                world.setBlock(i + 18, j + 1, k + 13, Blocks.stonebrick);
                world.setBlock(i + 18, j + 1, k + 14, Blocks.stonebrick);
                world.setBlock(i + 18, j + 1, k + 15, Blocks.stonebrick);
                world.setBlock(i + 18, j + 1, k + 16, Blocks.stonebrick);
                world.setBlock(i + 18, j + 1, k + 17, Blocks.stonebrick);
                world.setBlock(i + 18, j + 2, k + 0, Blocks.stonebrick);
                world.setBlock(i + 18, j + 2, k + 1, Blocks.stonebrick);
                world.setBlock(i + 18, j + 2, k + 2, Blocks.stonebrick);
                world.setBlock(i + 18, j + 2, k + 3, Blocks.stonebrick);
                world.setBlock(i + 18, j + 2, k + 4, Blocks.stone_brick_stairs, 3, 2);
                world.setBlock(i + 18, j + 2, k + 5, Blocks.stone_brick_stairs, 2, 2);
                world.setBlock(i + 18, j + 2, k + 6, Blocks.stonebrick);
                world.setBlock(i + 18, j + 2, k + 7, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 18, j + 2, k + 10, Blocks.stone_slab, 13, 2);
                world.setBlock(i + 18, j + 2, k + 11, Blocks.stonebrick);
                world.setBlock(i + 18, j + 2, k + 12, Blocks.stone_brick_stairs, 3, 2);
                world.setBlock(i + 18, j + 2, k + 13, Blocks.stone_brick_stairs, 2, 2);
                world.setBlock(i + 18, j + 2, k + 14, Blocks.stonebrick);
                world.setBlock(i + 18, j + 2, k + 15, Blocks.stonebrick);
                world.setBlock(i + 18, j + 2, k + 16, Blocks.stonebrick);
                world.setBlock(i + 18, j + 2, k + 17, Blocks.stonebrick);
                world.setBlock(i + 18, j + 3, k + 0, Blocks.stonebrick);
                world.setBlock(i + 18, j + 3, k + 1, Blocks.stonebrick);
                world.setBlock(i + 18, j + 3, k + 2, Blocks.stonebrick);
                world.setBlock(i + 18, j + 3, k + 3, Blocks.stonebrick);
                world.setBlock(i + 18, j + 3, k + 4, Blocks.stone_brick_stairs, 7, 2);
                world.setBlock(i + 18, j + 3, k + 5, Blocks.stone_brick_stairs, 6, 2);
                world.setBlock(i + 18, j + 3, k + 6, Blocks.stonebrick);
                world.setBlock(i + 18, j + 3, k + 7, Blocks.stonebrick);
                world.setBlock(i + 18, j + 3, k + 8, Blocks.stone_brick_stairs, 7, 2);
                world.setBlock(i + 18, j + 3, k + 9, Blocks.stone_brick_stairs, 6, 2);
                world.setBlock(i + 18, j + 3, k + 10, Blocks.stonebrick);
                world.setBlock(i + 18, j + 3, k + 11, Blocks.stonebrick);
                world.setBlock(i + 18, j + 3, k + 12, Blocks.stone_brick_stairs, 7, 2);
                world.setBlock(i + 18, j + 3, k + 13, Blocks.stone_brick_stairs, 6, 2);
                world.setBlock(i + 18, j + 3, k + 14, Blocks.stonebrick);
                world.setBlock(i + 18, j + 3, k + 15, Blocks.stonebrick);
                world.setBlock(i + 18, j + 3, k + 16, Blocks.stonebrick);
                world.setBlock(i + 18, j + 3, k + 17, Blocks.stonebrick);
 
                return true;
        }
}